# Site settings
title: Igor Klafke
email: your-email@yourdomain.com
description: "Uma cadeia de caracteres em formato incorreto"
baseurl: ""
url: "http://www.igorklafke.com"
twitter_username: igorklafke
github_username:  igorklafke
facebook_username:  igorklafke

# Build settings
markdown: kramdown
permalink: /blog/:title.html
paginate: 5
exclude: ["node_modules"]
